# .graphclientrc.yml
sources:
  - name: YourContract
    handler:
      graphql:
        endpoint: https://gateway.thegraph.com/api/bc94fce129c4d2c8714d45afac9ba23a/subgraphs/id/cHssgqLpdhAvNBBdiq1w1dGbYWAhmggPpcpCoXNEpWJ
documents:
  - ./graphql/GetNations.gql
